version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "incident-merge"
s3_bucket = "sam-artifacts-dev-kesse"
s3_prefix = "incident-merge"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM CAPABILITY_NAMED_IAM"
parameter_overrides = "ProjectTag=\"incident-app\" GitRepoUrl=\"https://github.com/drex7/cmrp-frontend.git\" GitHubTokenSecret=\"cmrp-frontend/token\""
image_repositories = []

[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "incidence-dev"
s3_bucket = "sam-artifacts-dev"
s3_prefix = "incidence"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM CAPABILITY_NAMED_IAM"

[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "incidence-prod"
s3_bucket = "sam-artifacts-prod"
s3_prefix = "incidence"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_IAM CAPABILITY_NAMED_IAM"

