AWSTemplateFormatVersion: "2010-09-09"
Description: "Minimal CloudFormation stack to provision a free AWS resource (S3 bucket) for testing SAM pipeline config."

Resources:
  TestS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "dispose-later-bucket-${AWS::AccountId}-${AWS::Region}"

Outputs:
  BucketName:
    Description: "Name of the S3 bucket created"
    Value: !Ref TestS3Bucket
